ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }
    application {
        modules = [ no.esotericgames.quotes.server.ApplicationKt.module ]
    }
}

storage {
    host = "localhost"
    host = ${?DB_HOST}
    port = 5432
    port = ${?DB_PORT}
    database = "quotes"
    database = ${?DB_NAME}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
}
